[general]
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/google-light.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 13.5

[font.offset]
x = 0
y = 1

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"

[window]
opacity = 0.95
decorations = "buttonless"

[window.dimensions]
columns = 145
lines = 35

[terminal.shell]
program ="/usr/bin/fish"
